# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b924daa41467ee89528d95e4d1a6ab0d770d16698e712a2118f57ec3341c3366655cd7baa215c4da42ffe14deaf8d92b3908e95c7eefe674b2221b2f9e91d09

test:
  secret_key_base: ad9267d8ffc3c3e059514c65e6628a3ea7c0d9596c3037d4d514ee6b6d067d3ad4baef286957326b11056bc8c14f03a18f605a3c010a984924b22441499fa8b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
